// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cndoespvwkvtinisgcey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZG9lc3B2d2t2dGluaXNnY2V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDc3NjYsImV4cCI6MjA2ODgyMzc2Nn0.8X7c1buoXohTWa5IfBgl1ST0fbG_kHcXMTsuD98xcSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});