//
//  ContactManager.h
//  Bees Chest
//
//  Created by Billy Irwin on 1/17/14.
//  Copyright (c) 2014 Arbrr. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <AddressBook/AddressBook.h>
#import <Contacts/Contacts.h>
#import "Contact.h"
#import "Tag.h"

@interface ContactManager : NSObject

@property (strong, nonatomic) NSMutableArray *contacts;
@property (strong, nonatomic) NSMutableDictionary *tagIndex;
@property (strong, nonatomic) NSString *facebookAccessToken;
@property (nonatomic, readonly) BOOL isLoadingContacts;
@property (nonatomic, readonly) BOOL isEnhancingWithFacebook;
@property (nonatomic, readonly) CGFloat enhancementProgress;
@property (strong, nonatomic) NSMutableArray *autoGeneratedTags;

+ (ContactManager*)singleton;

// Load contacts from phone
- (void)loadContactsFromAddressBookWithCompletion:(void(^)(BOOL success, NSError *error))completion;

// Facebook integration
- (void)setFacebookAccessToken:(NSString *)token;
- (BOOL)hasFacebookAccessToken;
- (void)clearFacebookAccessToken;

// Enhance contacts with Facebook data
- (void)enhanceContactsWithFacebookData:(void(^)(BOOL success, NSArray *enhancedContacts, NSError *error))completion;

// Tag related methods
- (void)generateTagsFromContact:(Contact *)contact;
- (NSArray *)getTagsForContact:(Contact *)contact;
- (NSArray *)getContactsWithTag:(Tag *)tag;
- (NSArray *)filterContactsByTags:(NSArray *)tags;

// Utility methods
- (void)saveContactsToLocalStorage;
- (void)loadContactsFromLocalStorage;
- (void)clearAllData;

@end
